import { demoMedia, type DemoMediaAsset } from "@/content/demo-assets/media";
import type { CatalogProduct } from "@/content/catalog/types";

type ProductSource = Omit<
  CatalogProduct,
  "badges" | "characteristics" | "media"
> & {
  media: readonly [DemoMediaAsset, ...DemoMediaAsset[]];
  badges?: CatalogProduct["badges"];
};

function defineProduct(source: ProductSource): CatalogProduct {
  return {
    ...source,
    badges: source.badges ?? [],
    characteristics: [
      { label: "Capacità", value: `${source.capacityMl} ml` },
      {
        label: "Gradazione",
        value: source.alcoholPercentage
          ? `${source.alcoholPercentage}% Vol.`
          : "Non dichiarata",
      },
      { label: "Paese", value: source.country },
      { label: "Tipologia", value: source.subcategory },
    ],
  };
}

export const catalogProducts = [
  defineProduct({
    code: "AB0740",
    slug: "the-macallan-12-double-cask",
    name: "The Macallan 12 Double Cask",
    brandSlug: "the-macallan",
    categorySlug: "whisky-whiskey",
    subcategory: "Single Malt Scotch",
    capacityMl: 700,
    alcoholPercentage: "40",
    country: "Scozia",
    producer: "The Macallan Distillers",
    netPriceMinor: 7_462n,
    stockQuantity: 55,
    isNew: false,
    isLimited: false,
    media: [demoMedia.whiskyCellar, demoMedia.curation],
    overview:
      "Un single malt dello Speyside che unisce la rotondità del rovere americano alla profondità delle botti europee ex sherry.",
    tastingNotes:
      "Miele, agrumi canditi e zenzero anticipano vaniglia, uva passa e una chiusura morbida di rovere speziato.",
    service:
      "Servire liscio in un calice da degustazione; poche gocce d’acqua possono aprirne le note più dolci.",
    origin:
      "Speyside, Scozia. Maturazione in una combinazione di botti di rovere americano ed europeo.",
    pairings: ["Cioccolato fondente", "Frutta secca", "Formaggi stagionati"],
  }),
  defineProduct({
    code: "AB0741",
    slug: "the-macallan-15-double-cask",
    name: "The Macallan 15 Double Cask",
    brandSlug: "the-macallan",
    categorySlug: "whisky-whiskey",
    subcategory: "Single Malt Scotch",
    capacityMl: 700,
    alcoholPercentage: "43",
    country: "Scozia",
    producer: "The Macallan Distillers",
    netPriceMinor: 16_078n,
    stockQuantity: 58,
    isNew: false,
    isLimited: true,
    badges: ["Selezione"],
    media: [demoMedia.rareCollection, demoMedia.whiskyCellar],
    overview:
      "Una maturazione più lunga e armonica, in cui frutta secca, legni dolci e spezie si integrano con grande misura.",
    tastingNotes:
      "Uvetta, cannella e butterscotch si distendono su note di mela cotta, cioccolato e rovere elegante.",
    service:
      "Ideale liscio, a temperatura ambiente, dopo alcuni minuti di ossigenazione nel calice.",
    origin:
      "Speyside, Scozia. Affinato in botti ex sherry selezionate per la gamma Double Cask.",
    pairings: ["Praline al cacao", "Noci pecan", "Sigaro delicato"],
  }),
  defineProduct({
    code: "AB0679",
    slug: "the-macallan-18-double-cask",
    name: "The Macallan 18 Double Cask",
    brandSlug: "the-macallan",
    categorySlug: "bottiglie-rare",
    subcategory: "Single Malt Scotch",
    capacityMl: 700,
    alcoholPercentage: "43",
    country: "Scozia",
    producer: "The Macallan Distillers",
    netPriceMinor: 39_202n,
    stockQuantity: 59,
    isNew: true,
    isLimited: true,
    badges: ["Nuovo", "Edizione limitata"],
    media: [demoMedia.rareCollection, demoMedia.whiskyCellar],
    overview:
      "Un’espressione da collezione, profonda e composta, in cui diciotto anni di maturazione costruiscono trama e persistenza.",
    tastingNotes:
      "Arancia matura, zenzero, caramello e frutta secca, con un finale lungo di spezie dolci e rovere lucidato.",
    service:
      "Da degustare lentamente, liscio, in un calice ampio che ne favorisca l’evoluzione aromatica.",
    origin:
      "Speyside, Scozia. Doppia maturazione in rovere americano ed europeo ex sherry.",
    pairings: ["Cioccolato 75%", "Datteri Medjoul", "Meditazione"],
  }),
  defineProduct({
    code: "AB2322",
    slug: "the-macallan-rare-cask-2023",
    name: "The Macallan Rare Cask 2023",
    brandSlug: "the-macallan",
    categorySlug: "bottiglie-rare",
    subcategory: "Rare Cask",
    capacityMl: 700,
    alcoholPercentage: "43",
    country: "Scozia",
    producer: "The Macallan Distillers",
    netPriceMinor: 34_952n,
    stockQuantity: 65,
    isNew: false,
    isLimited: true,
    badges: ["Edizione limitata"],
    media: [demoMedia.rareCollection, demoMedia.curation],
    overview:
      "Una selezione di botti rare orientata alla ricchezza, alla concentrazione e alla firma più opulenta della maison.",
    tastingNotes:
      "Uva passa, vaniglia scura, mela speziata e cioccolato, con una chiusura calda e avvolgente.",
    service:
      "Liscio, senza ghiaccio, lasciando riposare il distillato per coglierne le stratificazioni.",
    origin:
      "Speyside, Scozia. Release 2023 composta da botti selezionate per intensità aromatica.",
    pairings: ["Cioccolato fondente", "Fichi secchi", "Fine pasto"],
  }),
  defineProduct({
    code: "AB3952",
    slug: "yamazaki-12-years-old",
    name: "Yamazaki 12 Years Old",
    brandSlug: "yamazaki",
    categorySlug: "whisky-whiskey",
    subcategory: "Japanese Single Malt",
    capacityMl: 700,
    alcoholPercentage: "43",
    country: "Giappone",
    producer: "Suntory Yamazaki Distillery",
    netPriceMinor: 17_365n,
    stockQuantity: 83,
    isNew: false,
    isLimited: false,
    badges: ["Selezione"],
    media: [demoMedia.whiskyCellar, demoMedia.ginTea],
    overview:
      "Un single malt giapponese raffinato, capace di combinare frutto, spezia e una sottile componente orientale.",
    tastingNotes:
      "Pesca, ananas, pompelmo e chiodo di garofano, con un finale di zenzero dolce e legno Mizunara.",
    service:
      "Liscio o con un singolo cubo di ghiaccio cristallino; eccellente anche in un highball essenziale.",
    origin:
      "Shimamoto, Osaka. La prima distilleria di malt whisky del Giappone.",
    pairings: ["Sushi affumicato", "Mandorle", "Cioccolato al latte"],
  }),
  defineProduct({
    code: "AB6895",
    slug: "yamazaki-18-years-old",
    name: "Yamazaki 18 Years Old",
    brandSlug: "yamazaki",
    categorySlug: "bottiglie-rare",
    subcategory: "Japanese Single Malt",
    capacityMl: 700,
    alcoholPercentage: "43",
    country: "Giappone",
    producer: "Suntory Yamazaki Distillery",
    netPriceMinor: 60_644n,
    stockQuantity: 51,
    isNew: true,
    isLimited: true,
    badges: ["Nuovo", "Edizione limitata"],
    media: [demoMedia.rareCollection, demoMedia.ginTea],
    overview:
      "Una delle espressioni più ricercate del whisky giapponese, profonda e setosa, costruita attraverso una lunga maturazione.",
    tastingNotes:
      "Frutti rossi maturi, albicocca, cacao e incenso, seguiti da spezie, legni nobili e un finale persistente.",
    service: "Da degustare liscio, lentamente, in un momento dedicato.",
    origin:
      "Shimamoto, Osaka. Blend di malt whisky maturati almeno diciotto anni.",
    pairings: ["Cioccolato monorigine", "Frutta candita", "Meditazione"],
  }),
  defineProduct({
    code: "AB3464",
    slug: "lagavulin-8-years-old",
    name: "Lagavulin 8 Years Old",
    brandSlug: "lagavulin",
    categorySlug: "whisky-whiskey",
    subcategory: "Single Malt Scotch",
    capacityMl: 700,
    alcoholPercentage: "48",
    country: "Scozia",
    producer: "Lagavulin Distillery",
    netPriceMinor: 4_535n,
    stockQuantity: 36,
    isNew: false,
    isLimited: false,
    media: [demoMedia.whiskyCellar, demoMedia.rumCellar],
    overview:
      "Un Islay energico e verticale, con torba nitida, mineralità e un malto sorprendentemente luminoso.",
    tastingNotes:
      "Fumo secco, scorza di limone, pepe e cenere, sostenuti da cereali dolci e una traccia marina.",
    service:
      "Liscio o con qualche goccia d’acqua per distendere il lato agrumato.",
    origin:
      "Islay, Scozia. Otto anni di maturazione e imbottigliamento a 48% Vol.",
    pairings: ["Ostriche", "Salmone affumicato", "Formaggi erborinati"],
  }),
  defineProduct({
    code: "AB0591",
    slug: "lagavulin-16-years-old",
    name: "Lagavulin 16 Years Old",
    brandSlug: "lagavulin",
    categorySlug: "whisky-whiskey",
    subcategory: "Single Malt Scotch",
    capacityMl: 700,
    alcoholPercentage: "43",
    country: "Scozia",
    producer: "Lagavulin Distillery",
    netPriceMinor: 7_452n,
    stockQuantity: 49,
    isNew: false,
    isLimited: false,
    badges: ["Selezione"],
    media: [demoMedia.whiskyCellar, demoMedia.curation],
    overview:
      "Un riferimento di Islay, intenso ma equilibrato, in cui torba, mare e dolcezza di malto trovano una forma compiuta.",
    tastingNotes:
      "Fumo di torba, alghe, frutta secca e vaniglia, con un finale lungo, salino e speziato.",
    service:
      "Liscio, con tempo nel bicchiere; una piccola aggiunta d’acqua ne amplia la parte dolce.",
    origin: "Islay, Scozia. Sedici anni di maturazione in botte.",
    pairings: ["Formaggi blu", "Carne affumicata", "Cioccolato amaro"],
  }),
  defineProduct({
    code: "AB2126",
    slug: "glenfiddich-23-grand-cru",
    name: "Glenfiddich 23 Grand Cru",
    brandSlug: "glenfiddich",
    categorySlug: "bottiglie-rare",
    subcategory: "Single Malt Scotch",
    capacityMl: 700,
    alcoholPercentage: "43",
    country: "Scozia",
    producer: "Glenfiddich Distillery",
    netPriceMinor: 30_452n,
    stockQuantity: 81,
    isNew: false,
    isLimited: true,
    badges: ["Edizione limitata"],
    media: [demoMedia.rareCollection, demoMedia.whiskyCellar],
    overview:
      "Un single malt di ventitré anni rifinito in cuvée cask francesi, elegante nella presentazione e nel profilo.",
    tastingNotes:
      "Mela cotta, brioche, vaniglia e mandorla, con un finale raffinato di spezie e pasticceria.",
    service:
      "Liscio, in un calice ampio, come chiusura di una cena importante.",
    origin:
      "Speyside, Scozia. Maturazione di 23 anni e finish in botti di cuvée francese.",
    pairings: ["Pasticceria secca", "Comté", "Occasioni speciali"],
  }),
  defineProduct({
    code: "AB0396",
    slug: "diplomatico-ambassador",
    name: "Diplomatico Ambassador",
    brandSlug: "diplomatico",
    categorySlug: "bottiglie-rare",
    subcategory: "Rum Tradizionale da Melassa",
    capacityMl: 700,
    alcoholPercentage: "47",
    country: "Venezuela",
    producer: "Destilerías Unidas",
    netPriceMinor: 18_532n,
    stockQuantity: 85,
    isNew: false,
    isLimited: true,
    badges: ["Selezione"],
    media: [demoMedia.rareCollection, demoMedia.rumCellar],
    overview:
      "La cuvée di prestigio della casa, ricca e concentrata, con un affinamento che privilegia complessità e lunghezza.",
    tastingNotes:
      "Frutta scura, cacao, tabacco dolce e spezie, avvolti da una trama calda e persistente.",
    service:
      "Da meditazione, liscio, preferibilmente in un calice ballon contenuto.",
    origin:
      "Venezuela. Rum da melassa con lungo affinamento e finish selezionato.",
    pairings: ["Cioccolato fondente", "Sigaro", "Frutta secca"],
  }),
  defineProduct({
    code: "AB0059",
    slug: "diplomatico-reserva-exclusiva",
    name: "Diplomatico Reserva Exclusiva",
    brandSlug: "diplomatico",
    categorySlug: "rum-rhum",
    subcategory: "Rum Tradizionale da Melassa",
    capacityMl: 700,
    alcoholPercentage: "40",
    country: "Venezuela",
    producer: "Destilerías Unidas",
    netPriceMinor: 2_862n,
    stockQuantity: 60,
    isNew: false,
    isLimited: false,
    media: [demoMedia.rumCellar, demoMedia.curation],
    overview:
      "Un rum morbido e generoso, costruito su note dolci e speziate che lo rendono immediatamente riconoscibile.",
    tastingNotes:
      "Caramello, arancia candita, vaniglia e cacao, con una chiusura rotonda di spezie dolci.",
    service:
      "Liscio, con ghiaccio di grande formato oppure in miscelazione spirit-forward.",
    origin:
      "Venezuela. Assemblaggio di rum ottenuti con differenti metodi di distillazione.",
    pairings: ["Tiramisù", "Cioccolato", "Frutta secca"],
  }),
  defineProduct({
    code: "AB6087",
    slug: "zacapa-el-alma",
    name: "Zacapa El Alma",
    brandSlug: "zacapa",
    categorySlug: "rum-rhum",
    subcategory: "Rum Invecchiato",
    capacityMl: 700,
    alcoholPercentage: "40",
    country: "Guatemala",
    producer: "Ron Zacapa",
    netPriceMinor: 8_925n,
    stockQuantity: 49,
    isNew: false,
    isLimited: true,
    badges: ["Edizione limitata"],
    media: [demoMedia.rumCellar, demoMedia.rareCollection],
    overview:
      "Una release dedicata alle botti ex whiskey carbonizzate, intensa, tostata e avvolgente.",
    tastingNotes:
      "Mandorla tostata, cacao, vaniglia scura e cannella, con un finale caldo e leggermente affumicato.",
    service:
      "Liscio o con un singolo cubo di ghiaccio, dopo alcuni minuti nel bicchiere.",
    origin:
      "Guatemala. Affinamento in quota con passaggio in botti fortemente tostate.",
    pairings: ["Cacao", "Mandorle", "Dessert al caramello"],
  }),
  defineProduct({
    code: "AB6040",
    slug: "zacapa-edicion-negra",
    name: "Zacapa Edición Negra",
    brandSlug: "zacapa",
    categorySlug: "rum-rhum",
    subcategory: "Rum Invecchiato",
    capacityMl: 700,
    alcoholPercentage: "43",
    country: "Guatemala",
    producer: "Ron Zacapa",
    netPriceMinor: 5_740n,
    stockQuantity: 43,
    isNew: false,
    isLimited: false,
    media: [demoMedia.rumCellar, demoMedia.curation],
    overview:
      "L’interpretazione più scura e tostata della gamma, con una trama capace di sostenere la degustazione e l’abbinamento.",
    tastingNotes:
      "Frutta secca, caffè, legno tostato e spezie, con una dolcezza controllata e persistente.",
    service: "Liscio, con ghiaccio compatto o in un Old Fashioned di rum.",
    origin:
      "Guatemala. Rum affinato con un contributo marcato di botti tostate.",
    pairings: ["Caffè", "Cioccolato", "Carni glassate"],
  }),
  defineProduct({
    code: "AB6835",
    slug: "hendricks-another-gin",
    name: "Hendrick’s Another Gin",
    brandSlug: "au-vodka",
    categorySlug: "gin",
    subcategory: "London Dry Gin",
    capacityMl: 700,
    alcoholPercentage: null,
    country: "Scozia",
    producer: "William Grant & Sons",
    netPriceMinor: 3_062n,
    stockQuantity: 88,
    isNew: true,
    isLimited: false,
    badges: ["Nuovo"],
    media: [demoMedia.ginBotanicals, demoMedia.ginMediterranean],
    overview:
      "Una nuova interpretazione dell’universo Hendrick’s, floreale e botanica, pensata per un servizio fresco ed essenziale.",
    tastingNotes:
      "Ginepro, fiori bianchi, agrumi e una componente erbacea delicata, con chiusura asciutta.",
    service:
      "Con tonica neutra, molto ghiaccio e una guarnizione botanica misurata.",
    origin: "Girvan, Scozia. Release contemporanea della casa Hendrick’s.",
    pairings: ["Tonica dry", "Cetriolo", "Finger food salato"],
  }),
  defineProduct({
    code: "AB4704",
    slug: "hendricks-flora-adora",
    name: "Hendrick’s Flora Adora",
    brandSlug: "hendricks",
    categorySlug: "gin",
    subcategory: "London Dry Gin",
    capacityMl: 700,
    alcoholPercentage: "43.4",
    country: "Scozia",
    producer: "William Grant & Sons",
    netPriceMinor: 2_494n,
    stockQuantity: 74,
    isNew: false,
    isLimited: true,
    badges: ["Edizione limitata"],
    media: [demoMedia.ginBotanicals, demoMedia.ginTea],
    overview:
      "Una release floreale dalla personalità luminosa, che amplia la firma della casa senza perdere equilibrio.",
    tastingNotes:
      "Fiori freschi, erbe, ginepro e agrumi, con una coda morbida e profumata.",
    service: "Gin tonic con tonica leggera e una sottile scorza di limone.",
    origin: "Girvan, Scozia. Edizione limitata Cabinet of Curiosities.",
    pairings: ["Tonica mediterranea", "Frutti rossi", "Aperitivo"],
  }),
  defineProduct({
    code: "AB6737",
    slug: "caprisius-43",
    name: "Caprisius 43 Gin",
    brandSlug: "caprisius",
    categorySlug: "gin",
    subcategory: "Distilled Gin",
    capacityMl: 700,
    alcoholPercentage: "43",
    country: "Italia",
    producer: "Caprisius",
    netPriceMinor: 3_190n,
    stockQuantity: 66,
    isNew: true,
    isLimited: false,
    badges: ["Nuovo"],
    media: [demoMedia.ginMediterranean, demoMedia.ginBotanicals],
    overview:
      "Un distilled gin italiano dal profilo mediterraneo, nitido e aromatico, costruito per valorizzare le botaniche.",
    tastingNotes:
      "Ginepro, scorza di agrumi ed erbe mediterranee, con una chiusura fresca e asciutta.",
    service:
      "Con tonica secca e una scorza di agrume; interessante anche in un Martini essenziale.",
    origin: "Italia. Distillato con una selezione di botaniche mediterranee.",
    pairings: ["Tonica dry", "Olive", "Crudi di mare"],
  }),
  defineProduct({
    code: "AB6898",
    slug: "roku-noryo-tea-edition",
    name: "Roku Noryo Tea Edition",
    brandSlug: "roku",
    categorySlug: "gin",
    subcategory: "Contemporary Gin",
    capacityMl: 700,
    alcoholPercentage: "43",
    country: "Giappone",
    producer: "Suntory",
    netPriceMinor: 3_138n,
    stockQuantity: 82,
    isNew: true,
    isLimited: true,
    badges: ["Nuovo", "Edizione limitata"],
    media: [demoMedia.ginTea, demoMedia.ginBotanicals],
    overview:
      "Un’edizione ispirata alla stagione estiva giapponese, in cui il tè aggiunge precisione e profondità alla struttura del gin.",
    tastingNotes:
      "Tè verde, agrumi giapponesi, ginepro e una lieve nota tannica nel finale.",
    service:
      "Highball con soda o gin tonic con una tonica neutra e poco zuccherata.",
    origin: "Giappone. Edizione stagionale Noryo Tea.",
    pairings: ["Sashimi", "Tonica neutra", "Agrumi"],
  }),
  defineProduct({
    code: "AB6731",
    slug: "au-vodka-premium",
    name: "Au Vodka Premium",
    brandSlug: "hendricks",
    categorySlug: "vodka",
    subcategory: "Vodka Premium e Craft",
    capacityMl: 700,
    alcoholPercentage: "40",
    country: "Regno Unito",
    producer: "Au Vodka",
    netPriceMinor: 2_938n,
    stockQuantity: 30,
    isNew: true,
    isLimited: false,
    badges: ["Nuovo"],
    media: [demoMedia.curation, demoMedia.ginTea],
    overview:
      "Una vodka premium dal profilo pulito e morbido, proposta in una veste contemporanea.",
    tastingNotes:
      "Cereale delicato, lieve dolcezza e chiusura netta, con una consistenza setosa.",
    service: "Molto fredda, liscia oppure come base per Martini e long drink.",
    origin: "Regno Unito. Vodka di cereali imbottigliata a 40% Vol.",
    pairings: ["Caviale", "Salmoni affumicati", "Cocktail classici"],
  }),
  defineProduct({
    code: "AB1319",
    slug: "don-julio-1942",
    name: "Don Julio 1942",
    brandSlug: "don-julio",
    categorySlug: "tequila-mezcal",
    subcategory: "Tequila Añejo",
    capacityMl: 700,
    alcoholPercentage: "38",
    country: "Messico",
    producer: "Tequila Don Julio",
    netPriceMinor: 14_195n,
    stockQuantity: 87,
    isNew: false,
    isLimited: true,
    badges: ["Selezione"],
    media: [demoMedia.rareCollection, demoMedia.curation],
    overview:
      "Una tequila añejo iconica, morbida e stratificata, pensata esplicitamente per la degustazione.",
    tastingNotes:
      "Vaniglia, agave cotta, caramello e rovere dolce, con un finale lungo e caldo.",
    service: "Liscio, a temperatura ambiente, in un calice da distillato.",
    origin: "Jalisco, Messico. Tequila da agave blu con lungo affinamento.",
    pairings: ["Cioccolato", "Frutta tropicale", "Fine pasto"],
  }),
  defineProduct({
    code: "AB1332",
    slug: "don-julio-reposado",
    name: "Don Julio Reposado",
    brandSlug: "don-julio",
    categorySlug: "tequila-mezcal",
    subcategory: "Tequila Reposado",
    capacityMl: 700,
    alcoholPercentage: "38",
    country: "Messico",
    producer: "Tequila Don Julio",
    netPriceMinor: 4_120n,
    stockQuantity: 93,
    isNew: false,
    isLimited: false,
    media: [demoMedia.curation, demoMedia.ginMediterranean],
    overview:
      "Una tequila reposado equilibrata, in cui freschezza dell’agave e morbidezza del legno si incontrano.",
    tastingNotes:
      "Agave cotta, vaniglia, pepe bianco e agrumi, con una chiusura pulita e leggermente speziata.",
    service: "Liscio, con ghiaccio o in una Margarita più strutturata.",
    origin: "Jalisco, Messico. Riposo in rovere prima dell’imbottigliamento.",
    pairings: ["Tacos di pesce", "Agrumi", "Cioccolato bianco"],
  }),
  defineProduct({
    code: "AB6746",
    slug: "clase-azul-gold",
    name: "Clase Azul Gold",
    brandSlug: "clase-azul",
    categorySlug: "bottiglie-rare",
    subcategory: "Tequila Joven e Oro",
    capacityMl: 700,
    alcoholPercentage: "40",
    country: "Messico",
    producer: "Clase Azul México",
    netPriceMinor: 55_488n,
    stockQuantity: 49,
    isNew: true,
    isLimited: true,
    badges: ["Nuovo", "Edizione limitata"],
    media: [demoMedia.rareCollection, demoMedia.curation],
    overview:
      "Una tequila da collezione che unisce distillato e decanter, con un profilo morbido e una presentazione scenografica ma misurata.",
    tastingNotes:
      "Mela verde, fichi, caramello, zenzero e cacao, con una tessitura ricca e persistente.",
    service: "Liscio, in piccoli calici, lasciando ossigenare il distillato.",
    origin:
      "Jalisco, Messico. Assemblaggio di tequila con differenti maturazioni.",
    pairings: ["Foie gras", "Cioccolato", "Frutta secca"],
  }),
  defineProduct({
    code: "AB5519",
    slug: "clase-azul-anejo",
    name: "Clase Azul Añejo",
    brandSlug: "clase-azul",
    categorySlug: "bottiglie-rare",
    subcategory: "Tequila Añejo",
    capacityMl: 700,
    alcoholPercentage: "40",
    country: "Messico",
    producer: "Clase Azul México",
    netPriceMinor: 81_738n,
    stockQuantity: 87,
    isNew: false,
    isLimited: true,
    badges: ["Edizione limitata"],
    media: [demoMedia.rareCollection, demoMedia.curation],
    overview:
      "La massima espressione della linea, racchiusa in un decanter artigianale e costruita per il collezionismo.",
    tastingNotes:
      "Agave cotta, cannella, cacao, legno e frutta matura, con un finale particolarmente lungo.",
    service: "Da meditazione, liscio, senza ghiaccio.",
    origin: "Jalisco, Messico. Tequila añejo in decanter da collezione.",
    pairings: ["Cioccolato fondente", "Datteri", "Meditazione"],
  }),
  defineProduct({
    code: "AB6444",
    slug: "ilegal-mezcal-anejo",
    name: "Ilegal Mezcal Añejo",
    brandSlug: "ilegal",
    categorySlug: "tequila-mezcal",
    subcategory: "Mezcal Artesanal",
    capacityMl: 700,
    alcoholPercentage: "40",
    country: "Messico",
    producer: "Ilegal Mezcal",
    netPriceMinor: 7_625n,
    stockQuantity: 91,
    isNew: false,
    isLimited: false,
    media: [demoMedia.curation, demoMedia.rumCellar],
    overview:
      "Un mezcal añejo in cui la componente affumicata incontra la morbidezza e le spezie dell’affinamento.",
    tastingNotes:
      "Agave arrostita, cacao, pepe, legno dolce e fumo sottile, con una chiusura calda.",
    service: "Liscio, in copita, accompagnato da acqua fresca.",
    origin: "Oaxaca, Messico. Mezcal artigianale affinato in legno.",
    pairings: ["Cioccolato al sale", "Carni alla brace", "Agrumi"],
  }),
  defineProduct({
    code: "AB0977",
    slug: "camus-xo",
    name: "Camus XO",
    brandSlug: "camus",
    categorySlug: "cognac",
    subcategory: "Cognac XO",
    capacityMl: 700,
    alcoholPercentage: "40",
    country: "Francia",
    producer: "Maison Camus",
    netPriceMinor: 14_800n,
    stockQuantity: 42,
    isNew: false,
    isLimited: true,
    badges: ["Selezione"],
    media: [demoMedia.rareCollection, demoMedia.whiskyCellar],
    overview:
      "Un Cognac XO ampio e raffinato, costruito sulla ricchezza aromatica e sulla morbidezza dell’assemblaggio.",
    tastingNotes:
      "Albicocca, miele, spezie dolci e cacao, con note floreali e un finale di legno fine.",
    service: "Liscio, in calice tulipano, a temperatura ambiente.",
    origin: "Cognac, Francia. Assemblaggio XO della maison Camus.",
    pairings: ["Cioccolato al latte", "Formaggi erborinati", "Fine pasto"],
  }),
  defineProduct({
    code: "AB1903",
    slug: "janneau-grand-armagnac-25",
    name: "Janneau Grand Armagnac 25 Years",
    brandSlug: "janneau",
    categorySlug: "armagnac",
    subcategory: "Armagnac",
    capacityMl: 700,
    alcoholPercentage: "43",
    country: "Francia",
    producer: "Maison Janneau",
    netPriceMinor: 8_515n,
    stockQuantity: 31,
    isNew: false,
    isLimited: true,
    badges: ["Selezione"],
    media: [demoMedia.whiskyCellar, demoMedia.rareCollection],
    overview:
      "Venticinque anni di maturazione danno forma a un Armagnac profondo, caldo e intensamente territoriale.",
    tastingNotes:
      "Prugna, noce, vaniglia, cacao e spezie, con una trama morbida e un finale persistente.",
    service:
      "Liscio, in calice tulipano, dopo qualche minuto di ossigenazione.",
    origin: "Guascogna, Francia. Grand Armagnac invecchiato 25 anni.",
    pairings: ["Prugne secche", "Cioccolato", "Formaggi stagionati"],
  }),
  defineProduct({
    code: "AB1320",
    slug: "amaro-montenegro",
    name: "Amaro Montenegro",
    brandSlug: "24kt",
    categorySlug: "amari",
    subcategory: "Amari Regionali Classici",
    capacityMl: 700,
    alcoholPercentage: "23",
    country: "Italia",
    producer: "Gruppo Montenegro",
    netPriceMinor: 1_334n,
    stockQuantity: 82,
    isNew: false,
    isLimited: false,
    media: [demoMedia.ginBotanicals, demoMedia.curation],
    overview:
      "Un classico italiano dal profilo equilibrato, aromatico e accessibile, capace di attraversare servizio tradizionale e miscelazione.",
    tastingNotes:
      "Arancia dolce, erbe, spezie leggere e una nota floreale, con finale morbido e piacevolmente amaro.",
    service: "Liscio, con ghiaccio e scorza d’arancia oppure in miscelazione.",
    origin: "Italia. Amaro alle erbe e spezie della tradizione bolognese.",
    pairings: ["Cioccolato", "Pasticceria secca", "Dopocena"],
  }),
  defineProduct({
    code: "AB4172",
    slug: "cocchi-americano-bianco",
    name: "Cocchi Americano Bianco",
    brandSlug: "cocchi",
    categorySlug: "vermouth",
    subcategory: "Vermouth Bianco",
    capacityMl: 750,
    alcoholPercentage: "16.5",
    country: "Italia",
    producer: "Giulio Cocchi",
    netPriceMinor: 1_612n,
    stockQuantity: 72,
    isNew: false,
    isLimited: false,
    media: [demoMedia.rumCellar, demoMedia.ginMediterranean],
    overview:
      "Un aperitivo a base vino dalla firma agrumata e amaricante, preciso nel servizio liscio e nei cocktail classici.",
    tastingNotes:
      "Agrumi, erbe, spezie e una vena amaricante di china, sostenuti da freschezza vinosa.",
    service:
      "Freddo, con ghiaccio, soda e scorza d’arancia oppure in miscelazione.",
    origin:
      "Piemonte, Italia. Aperitivo di vino aromatizzato secondo ricetta storica.",
    pairings: ["Olive", "Acciughe", "Aperitivo"],
  }),
  defineProduct({
    code: "AB5243",
    slug: "carlo-alberto-riserva-bianco",
    name: "Carlo Alberto Riserva Bianco",
    brandSlug: "ciemme",
    categorySlug: "vermouth",
    subcategory: "Vermouth Bianco",
    capacityMl: 750,
    alcoholPercentage: "18",
    country: "Italia",
    producer: "Compagnia dei Caraibi",
    netPriceMinor: 2_088n,
    stockQuantity: 62,
    isNew: false,
    isLimited: false,
    badges: ["Selezione"],
    media: [demoMedia.rumCellar, demoMedia.ginBotanicals],
    overview:
      "Un vermouth bianco riserva complesso e gastronomico, costruito su una base vinosa elegante e botaniche ben integrate.",
    tastingNotes:
      "Fiori, agrumi, erbe alpine e spezie dolci, con equilibrio tra morbidezza e finale amaricante.",
    service:
      "Freddo, con ghiaccio e scorza di limone oppure in un Martini più morbido.",
    origin: "Piemonte, Italia. Vermouth bianco della linea Riserva.",
    pairings: ["Formaggi", "Mandorle", "Aperitivo"],
  }),
  defineProduct({
    code: "AB1369",
    slug: "select-aperitivo",
    name: "Select Aperitivo",
    brandSlug: "select",
    categorySlug: "aperitivi",
    subcategory: "Aperitivi Amari e Red Bitter",
    capacityMl: 700,
    alcoholPercentage: "17.5",
    country: "Italia",
    producer: "Select",
    netPriceMinor: 996n,
    stockQuantity: 88,
    isNew: false,
    isLimited: false,
    media: [demoMedia.ginMediterranean, demoMedia.rumCellar],
    overview:
      "L’aperitivo veneziano dal colore rubino e dal profilo agrumato, speziato e piacevolmente amaro.",
    tastingNotes:
      "Arancia amara, rabarbaro, erbe e spezie, con una dolcezza contenuta.",
    service: "Con soda e oliva verde oppure nello Spritz veneziano.",
    origin: "Venezia, Italia. Aperitivo amaro della tradizione lagunare.",
    pairings: ["Cicchetti", "Olive verdi", "Aperitivo"],
  }),
  defineProduct({
    code: "AB6526",
    slug: "24kt-crema-cioccolato-grappa",
    name: "24KT Crema Cioccolato e Grappa",
    brandSlug: "montenegro",
    categorySlug: "liquori",
    subcategory: "Liquori al Cacao e Cioccolato",
    capacityMl: 700,
    alcoholPercentage: "17",
    country: "Italia",
    producer: "24KT",
    netPriceMinor: 1_180n,
    stockQuantity: 65,
    isNew: true,
    isLimited: false,
    badges: ["Nuovo"],
    media: [demoMedia.curation, demoMedia.rumCellar],
    overview:
      "Una crema liquorosa morbida e golosa, in cui cacao e grappa trovano un equilibrio da fine pasto.",
    tastingNotes:
      "Cioccolato, cacao e una lieve nota di vinaccia, con consistenza cremosa.",
    service:
      "Ben fredda, liscia oppure in accompagnamento a dessert al cucchiaio.",
    origin: "Italia. Liquore cremoso al cioccolato e grappa.",
    pairings: ["Gelato", "Tiramisù", "Caffè"],
  }),
  defineProduct({
    code: "AB6187",
    slug: "ciemme-grappa-friuldoro-miniature",
    name: "Ciemme Grappa Friuldoro Miniature",
    brandSlug: "carlo-alberto",
    categorySlug: "grappe",
    subcategory: "Grappa Affinata",
    capacityMl: 30,
    alcoholPercentage: "40",
    country: "Italia",
    producer: "Ciemme",
    netPriceMinor: 2_579n,
    stockQuantity: 97,
    isNew: false,
    isLimited: false,
    media: [demoMedia.curation, demoMedia.whiskyCellar],
    overview:
      "Una confezione di miniature dedicata alla grappa affinata, adatta al regalo e alla degustazione condivisa.",
    tastingNotes:
      "Vinaccia, frutta secca e spezie leggere, con una chiusura calda e pulita.",
    service: "A temperatura ambiente in piccoli calici da distillato.",
    origin:
      "Friuli-Venezia Giulia, Italia. Grappa affinata in formato miniature.",
    pairings: ["Caffè", "Cioccolato", "Pasticceria secca"],
  }),
] as const satisfies readonly CatalogProduct[];
