export const brandAssets = {
  status: "source-provided",
  wordmark: "/brand/mietto-logo.png",
  horizontalLogo: "/brand/mietto-logo.png",
  compactLogo: "/brand/mietto-logo.png",
  darkBackgroundLogo: "/brand/mietto-logo.png",
  monochromeLogo: null,
  faviconIco: "/favicon.ico",
  favicon16: "/brand/favicon-16.png",
  favicon32: "/brand/favicon-32.png",
  favicon48: "/brand/favicon-48.png",
  appleTouchIcon: "/brand/apple-touch-icon.png",
  androidIcon192: "/brand/icon-192.png",
  androidIcon512: "/brand/icon-512.png",
  openGraphImage: "/opengraph-image",
} as const;
