import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

function source(path: string) {
  return readFileSync(resolve(path), "utf8");
}

describe("admin product inventory history UI", () => {
  const history = source(
    "src/features/admin/admin-product-inventory-history.tsx",
  );

  it("labels every supported movement type", () => {
    expect(history).toContain("Regolazione manuale");
    expect(history).toContain("Ordine evaso");
    expect(history).toContain("Riconciliazione riservati");
  });

  it("shows stock reserved and available changes", () => {
    expect(history).toContain('label="Stock totale"');
    expect(history).toContain('label="Riservati"');
    expect(history).toContain('label="Disponibili"');
    expect(history).toContain("formatDelta");
  });

  it("shows reason author and Italian timestamps", () => {
    expect(history).toContain("Motivazione");
    expect(history).toContain("Autore:");
    expect(history).toContain('"Europe/Rome"');
  });

  it("links movements generated by fulfilled orders", () => {
    expect(history).toContain("href={`/admin/ordini/${movement.orderNumber}`}");
    expect(history).toContain("Ordine {movement.orderNumber}");
  });

  it("supports products without movements", () => {
    expect(history).toContain("Nessun movimento di magazzino registrato.");
  });

  it("is rendered in the product detail page", () => {
    const page = source("src/app/admin/(dashboard)/prodotti/[id]/page.tsx");

    expect(page).toContain("AdminProductInventoryHistory");
    expect(page).toContain("movements={inventoryMovements}");
  });
});
